import Head from 'next/head'
import Header from '@/components/Header/Header'
import BannerTop from '@/components/BannerTop/BannerTop'
import Benefits from '@/components/Benefits/Benefits'
import OurPlatform from '@/components/OurPlatform/OurPlatform'
import Purpose from '@/components/Purpose/Purpose'
import Cta from '@/components/Cta/Cta'
import Download from '@/components/Download/Download'
import Footer from '@/components/Footer/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>meutudo. | Baixe o Aplicativo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <BannerTop />
      <Benefits />
      <OurPlatform />
      <Purpose />
      <Cta />
      <Download />
      <Footer />
      
    </>
  )
}


